let fs = require('fs')
fs.readdir(`../theme/`, (err, files) => {
    files.forEach((file) => {
        console.log(`"${file.split(".")[0]}": "${file}",`)
    })
});

let themeCSSFileMap = {
    "無": "Classic.css",
    "Solarized Dark PTT優化版": "Solarized-Dark-PTT.css",
    "Solarized Light PTT優化版": "Solarized-Light-PTT.css",
    "Apple Terminal": "Apple Terminal.css",
    "Argonaut": "Argonaut.css",
    "Birds Of Paradise": "Birds Of Paradise.css",
    "Blazer": "Blazer.css",
    "Chalkboard": "Chalkboard.css",
    "Ciapre": "Ciapre.css",
    "Dark Pastel": "Dark Pastel.css",
    "Desert": "Desert.css",
    "Espresso": "Espresso.css",
    "Fish Of Paradise": "Fish Of Paradise.css",
    "Fish Tank": "Fish Tank.css",
    "Grass": "Grass.css",
    "Highway": "Highway.css",
    "Homebrew": "Homebrew.css",
    "Hurtado": "Hurtado.css",
    "Ic Green Ppl": "Ic Green Ppl.css",
    "Idletoes": "Idletoes.css",
    "Igvita Desert": "Igvita Desert.css",
    "Igvita Light": "Igvita Light.css",
    "Invisibone": "Invisibone.css",
    "Kibble": "Kibble.css",
    "Liquid Carbon Transparent Inverse": "Liquid Carbon Transparent Inverse.css",
    "Liquid Carbon Transparent": "Liquid Carbon Transparent.css",
    "Liquid Carbon": "Liquid Carbon.css",
    "Man Page": "Man Page.css",
    "Mariana": "Mariana.css",
    "Monokai Dimmed": "Monokai Dimmed.css",
    "Monokai Soda": "Monokai Soda.css",
    "Monokai Stevelosh": "Monokai Stevelosh.css",
    "Neopolitan": "Neopolitan.css",
    "Novel": "Novel.css",
    "Ocean": "Ocean.css",
    "Papirus Dark": "Papirus Dark.css",
    "Pro": "Pro.css",
    "Red Sands": "Red Sands.css",
    "Seafoam Pastel": "Seafoam Pastel.css",
    "Solarized Darcula": "Solarized Darcula.css",
    "Solarized Dark": "Solarized Dark.css",
    "Solarized Light": "Solarized Light.css",
    "Sundried": "Sundried.css",
    "Sympfonic": "Sympfonic.css",
    "Teerb": "Teerb.css",
    "Terminal Basic": "Terminal Basic.css",
    "Thayer": "Thayer.css",
    "Tomorrow Night": "Tomorrow Night.css",
    "Tomorrow": "Tomorrow.css",
    "Twilight": "Twilight.css",
    "Vaughn": "Vaughn.css",
    "X Dotshare": "X Dotshare.css",
    "Zenburn": "Zenburn.css",
    "github": "github.css",
    "other": "other.css",
    "template": "template"
}